### ISSUE TITLE
Exclamation symbol 

### ISSUE THREAD

**Issue by oats22** [doofdoofsf/boulderweather#4]
Some recent feedback indicates that it isn’t immediately obvious to a user that a west wind direction is what triggers the exclamation point. There remains a bit of ambiguity given that wind speed could also be held liable for the exclamation symbol in the current format. I suggest we move the exclamation mark into the wind direction column, or even better, there could be a hover option over the exclamation symbol that would display a text box reading something along the lines of: “Caution: West Wind Indicated”

**Comment by W0mpRat** [comment]
I moved the wind indicator to the wind direction column.
